CREATE TABLE `special_quotation_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`systemTitle` varchar(500),
	`systemDescription` text,
	`kwRating` varchar(50),
	`setupType` varchar(100),
	`items` json,
	`subtotal` decimal(12,2),
	`vatRate` decimal(5,2),
	`discount` decimal(12,2),
	`remarks` text,
	`warrantyClaims` text,
	`paymentTerms` text,
	`paymentDetails` text,
	`deliveryTerms` text,
	`preparedBy` varchar(200),
	`contactInfo` text,
	`isActive` int NOT NULL DEFAULT 1,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `special_quotation_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `special_quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`templateId` int,
	`quotationNumber` varchar(50) NOT NULL,
	`date` timestamp,
	`customerName` varchar(200),
	`customerAddress` text,
	`systemTitle` varchar(500),
	`systemDescription` text,
	`kwRating` varchar(50),
	`setupType` varchar(100),
	`items` json,
	`subtotal` decimal(12,2),
	`vatRate` decimal(5,2),
	`vatAmount` decimal(12,2),
	`discount` decimal(12,2),
	`total` decimal(12,2),
	`remarks` text,
	`warrantyClaims` text,
	`paymentTerms` text,
	`paymentDetails` text,
	`deliveryTerms` text,
	`preparedBy` varchar(200),
	`contactInfo` text,
	`status` enum('draft','sent','accepted','rejected') NOT NULL DEFAULT 'draft',
	`createdBy` int,
	`createdByName` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `special_quotations_id` PRIMARY KEY(`id`),
	CONSTRAINT `special_quotations_quotationNumber_unique` UNIQUE(`quotationNumber`)
);
